/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#273647",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-primary-fixed": "#2a1700",
        "surface-container-low": "#0d1c2d",
        "surface-variant": "#273647",
        "on-primary": "#472a00",
        "surface": "#051424",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#8d0012",
        "secondary": "#4edea3",
        "primary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed-variant": "#930013",
        "on-secondary": "#003824",
        "tertiary-fixed": "#ffdad7",
        "surface-tint": "#ffb95f",
        "on-tertiary-fixed": "#410004",
        "surface-container-lowest": "#010f1f",
        "on-secondary-container": "#00311f",
        "on-primary-container": "#613b00",
        "inverse-surface": "#d4e4fa",
        "surface-dim": "#051424",
        "on-surface": "#d4e4fa",
        "tertiary-container": "#ff938c",
        "on-tertiary": "#68000a",
        "tertiary": "#ffbcb7",
        "secondary-fixed": "#6ffbbe",
        "outline-variant": "#534434",
        "on-background": "#d4e4fa",
        "outline": "#a08e7a",
        "on-secondary-fixed": "#002113",
        "surface-container-high": "#1c2b3c",
        "background": "#051424",
        "on-secondary-fixed-variant": "#005236",
        "secondary-container": "#00a572",
        "inverse-primary": "#855300",
        "primary-container": "#f59e0b",
        "surface-bright": "#2c3a4c",
        "surface-container": "#122131",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-fixed-variant": "#653e00",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "primary": "#ffc174",
        "inverse-on-surface": "#233143",
        "primary-fixed": "#ffddb8",
        "error-container": "#93000a",
        "on-surface-variant": "#d8c3ad"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "space-lg": "0.75rem",
        "space-md": "0.5rem",
        "gutter-compact": "0.125rem",
        "space-sm": "0.25rem",
        "margin": "0.5rem",
        "gutter": "0.25rem",
        "space-xl": "1rem",
        "space-xs": "0.125rem"
      },
      fontFamily: {
        "label-xs": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "data-mono-sm": ["JetBrains Mono", "monospace"],
        "data-mono-lg": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter", "sans-serif"],
        "data-mono-xl": ["JetBrains Mono", "monospace"],
        "data-mono-md": ["JetBrains Mono", "monospace"],
        "mono": ["JetBrains Mono", "monospace"],
        "sans": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-xs": ["10px", { lineHeight: "12px", letterSpacing: "0.04em", fontWeight: "600" }],
        "headline-md": ["14px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "600" }],
        "headline-xl": ["24px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["11px", { lineHeight: "14px", fontWeight: "400" }],
        "body-md": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "data-mono-sm": ["10px", { lineHeight: "12px", fontWeight: "500" }],
        "data-mono-lg": ["14px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg": ["18px", { lineHeight: "22px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "data-mono-xl": ["20px", { lineHeight: "24px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-mono-md": ["12px", { lineHeight: "16px", fontWeight: "500" }]
      }
    }
  },
  plugins: [],
}
